/* eslint-disable linebreak-style */
/* eslint-disable import/prefer-default-export */

export const questions = [
  {
    text: 'Working space for Windows is called:',
    answers: [
      { option: 'Recycle bin', correct: false },
      { option: 'Desktop', correct: true },
      { option: 'Taskbar', correct: false },
      { option: 'Start Menu', correct: false },
    ],
    points: 5,
    category: 'Computer Science',
    isCheckInput: false,
    inputQuestion: false,
  },
  {
    text: 'How many legs does a Spider have?',
    answers: [
      { option: '4', correct: false },
      { option: '6', correct: false },
      { option: '8', correct: true },
      { option: '10', correct: false },
    ],
    points: 5,
    category: 'Biology',
    isCheckInput: false,
    inputQuestion: false,
  },
  {
    text: 'At what temperature does water freeze?',
    answers: [
      { option: '-5°', correct: false },
      { option: '-10°', correct: false },
      { option: '5°', correct: false },
      { option: '0°', correct: true },
    ],
    points: 5,
    category: 'Science',
    isCheckInput: false,
    inputQuestion: false,
  },
  {
    text: 'Which planet is the closest to the Sun',
    answers: [
      { option: 'Mercury', correct: true },
      { option: 'Uranus', correct: false },
      { option: 'Jupiter', correct: false },
      { option: 'Earth', correct: false },
    ],
    points: 5,
    category: 'Astrology',
    isCheckInput: false,
    inputQuestion: false,
  },
  {
    text: 'Which ocean is the largest and deepest?',
    answers: [
      { option: 'Southern Ocean', correct: false },
      { option: 'Pacific Ocean', correct: true },
      { option: 'Atlantic Ocean', correct: false },
      { option: 'Indian Ocean', correct: false },
    ],
    points: 5,
    category: 'Geography',
    isCheckInput: false,
    inputQuestion: false,
  },
  {
    text: 'The World War II started in:',
    answers: [
      { option: '1945.', correct: false },
      { option: '1918.', correct: false },
      { option: '1939.', correct: true },
      { option: '1914.', correct: false },
    ],
    points: 5,
    category: 'History',
    isCheckInput: false,
    inputQuestion: false,
  },
  {
    text: 'Who is the most payed Athlete of All Time?',
    answers: [
      { option: 'Michael Schumaher', correct: false },
      { option: 'Tiger Woods', correct: false },
      { option: 'Floyd Mayweather', correct: false },
      { option: 'Michael Jordan', correct: true },
    ],
    points: 5,
    category: 'Sports',
    isCheckInput: false,
    inputQuestion: false,
  },
  {
    text: 'Which of these is a Mammal?',
    answers: [
      { option: 'Humpback Whale', correct: true },
      { option: 'Snake', correct: false },
      { option: 'Ostrich', correct: false },
      { option: 'Gorilla', correct: true },
    ],
    points: 2.5,
    category: 'Biology',
    isCheckInput: true,
    inputQuestion: false,
  },
  {
    text: 'Who are the boxers in this list?',
    answers: [
      { option: 'Connor McGregor', correct: false },
      { option: 'Mike Tyson', correct: true },
      { option: 'Khabib Nurmagomedov', correct: false },
      { option: 'Muhammad Ali', correct: true },
    ],
    points: 2.5,
    category: 'Sports',
    isCheckInput: true,
    inputQuestion: false,
  },
  {
    text: 'Which of these statements for Ancient Greece are true?',
    answers: [
      { option: 'Marathons came from Ancient Greek times', correct: true },
      { option: 'They believed in one God', correct: false },
      { option: 'They worshipped many Gods and Goddesses', correct: true },
      { option: 'The Ancient Greeks were famous for their Pyramids', correct: false },
    ],
    points: 2.5,
    category: 'History',
    isCheckInput: true,
    inputQuestion: false,
  },
  {
    text: 'The 2 most populated countries are:',
    answers: [
      { option: 'United States', correct: false },
      { option: 'India', correct: true },
      { option: 'China', correct: true },
      { option: 'Indonesia', correct: false },
    ],
    points: 2.5,
    category: 'Geography',
    isCheckInput: true,
    inputQuestion: false,
  },
  {
    text: 'The Air consists of mostly:',
    answers: [
      { option: 'Carbon Dioxide (CO2)', correct: false },
      { option: 'Water Wapor (H2O)', correct: false },
      { option: 'Nytrogen (N2)', correct: true },
      { option: 'Oxygen(O2)', correct: true },
    ],
    points: 2.5,
    category: 'Science',
    isCheckInput: true,
    inputQuestion: false,
  },
  {
    text: 'Which of these is hardware?',
    answers: [
      { option: 'Printer', correct: true },
      { option: 'Keyboard', correct: true },
      { option: 'Folder', correct: false },
      { option: 'Operating System', correct: false },
    ],
    points: 2.5,
    category: 'Computer Science',
    isCheckInput: true,
    inputQuestion: false,
  },
  {
    text: 'Who is the impostor ( Chicken, Pig, Cow, Fox)?',
    answer: 'Fox',
    points: 5,
    category: 'Biology',
    isCheckInput: false,
    inputQuestion: true,
  },
  {
    text: 'The city with the biggest population in the world is:',
    answer: 'Tokyo',
    points: 5,
    category: 'Geography',
    isCheckInput: false,
    inputQuestion: true,
  },
  {
    text: 'The fastest animal on land is:',
    answer: 'Cheetah',
    points: 5,
    category: 'Biology',
    isCheckInput: false,
    inputQuestion: true,
  },
  {
    text: 'Wich planet is the farthest from the sun?',
    answer: 'Pluto',
    points: 5,
    category: 'Astrology',
    isCheckInput: false,
    inputQuestion: true,
  },
  {
    text: 'How was the ruller of ancient Egypt called',
    answer: 'Pharaoh',
    points: 5,
    category: 'History',
    isCheckInput: false,
    inputQuestion: true,
  },
  {
    text: 'The record world record holder for the fastest 100m is:',
    answer: 'Usain Bolt',
    points: 5,
    category: 'Sports',
    isCheckInput: false,
    inputQuestion: true,
  },
  {
    text: 'Wich operating system is the most widely used?',
    answer: 'Windows',
    points: 5,
    category: 'Computer Science',
    isCheckInput: false,
    inputQuestion: true,
  },
];
